# Generated by Django 2.2.12 on 2020-04-22 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20200422_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='ferfc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datamodel_ferfc', to=settings.AUTH_USER_MODEL),
        ),
    ]
